dist: bionic
language: python
python:
  - '3.6'
  - '3.7'
before_install:
  - sudo apt update
  - sudo apt upgrade -y
install:
  - pip install -U pip setuptools pipenv invoke pylint
  - invoke deploy
before_script:
  - cp config/config_default.yml config/config_custom.yml
  - chmod +x main.py
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then invoke reformat; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pylint --jobs=0 --rc-file=./.pylintrc .; fi
  - invoke test

notifications:
  slack: cubesat-hq:6WEoaS8qIysyWmqygp4OFgH4

