# Simulate = whether or not core is running while running fake data
core:
    modules:
        A:
            - eps
            - command_ingest
        B:
            - antenna_deployer
        C:
            - aprs
            - iridium
            - telemetry
    dump_inteval: 3600
    sleep_interval: 1800

aprs:
    serial_port: /dev/ttyUSB0
    telem_timeout: 70
    message_spacing: 1
eps:
    looptime: 20
telemetry:
    buffer_size: 100
    max_packet_size: 170
iridium:
    serial_port: /dev/ttyUSB0
antenna:
    ANT_1: 0
    ANT_2: 1
    ANT_3: 2
    ANT_4: 3